//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int ID { get; set; }
        public string Empresa1 { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string DireccionNumero { get; set; }
        public string DireccionNumeroINT { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> EstatusID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> UltimoCambio { get; set; }
        public string RFC { get; set; }
        public string RutaImagen { get; set; }
        public Nullable<bool> CuotaHD { get; set; }
        public string userFTP { get; set; }
        public string passFTP { get; set; }
        public string FTP { get; set; }
        public string PassRegistroChecker { get; set; }
    }
}
