//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FivesEntities : DbContext
    {
        public FivesEntities()
            : base("name=FivesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Huella> Huella { get; set; }
        public virtual DbSet<Jornada> Jornada { get; set; }
        public virtual DbSet<JornadaD> JornadaD { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
    }
}
