//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class JornadaD
    {
        public Nullable<int> ID { get; set; }
        public int Dia { get; set; }
        public string Entrada { get; set; }
        public string Salida { get; set; }
    }
}
