//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int ID { get; set; }
        public string Persona { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string Imagen { get; set; }
        public string Notas { get; set; }
        public Nullable<int> PerfilID { get; set; }
        public string Contrasena { get; set; }
        public string ContrasenaConfirmacion { get; set; }
        public Nullable<int> EstatusID { get; set; }
        public Nullable<int> SucursalID { get; set; }
        public Nullable<int> AgenteID { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<int> cteID { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sesion { get; set; }
        public Nullable<int> Conectado { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
