//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int ID { get; set; }
        public string Personal1 { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Direccion { get; set; }
        public string DireccionNumero { get; set; }
        public string DireccionNumeroInt { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> CodigoPostalID { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<int> ZonaEconomicaID { get; set; }
        public string Rfc { get; set; }
        public string Curp { get; set; }
        public string Nss { get; set; }
        public string NoAfore { get; set; }
        public Nullable<int> AforeID { get; set; }
        public Nullable<int> FormaPagoID { get; set; }
        public Nullable<int> CtaDineroID { get; set; }
        public int SucursalID { get; set; }
        public string CuentaPago { get; set; }
        public Nullable<int> LugarNacimientoID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Pasaporte { get; set; }
        public string INE { get; set; }
        public string Licencia { get; set; }
        public Nullable<int> NivelAcademicoID { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> CentroCostosID { get; set; }
        public string ReportaAID { get; set; }
        public Nullable<int> JornadaID { get; set; }
        public Nullable<int> TipoSueldoID { get; set; }
        public Nullable<int> MonedaID { get; set; }
        public int EmpresaID { get; set; }
        public Nullable<int> UenID { get; set; }
        public Nullable<int> PeriodoTipoID { get; set; }
        public Nullable<double> SueldoDiario { get; set; }
        public Nullable<double> SDI { get; set; }
        public Nullable<double> SDIBimestral { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> VencimientoContrato { get; set; }
        public Nullable<System.DateTime> LicenciaVencimiento { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public Nullable<System.DateTime> UltimoPago { get; set; }
        public int EstatusID { get; set; }
        public Nullable<bool> Tienemovimientos { get; set; }
        public string CtaContable { get; set; }
        public string CtaRetencion { get; set; }
        public string CtaRetencion2 { get; set; }
        public Nullable<int> BancoID { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
        public Nullable<int> PuestoID { get; set; }
        public string InicioRelacionLaboralSat { get; set; }
        public string AntiguedadSat { get; set; }
        public Nullable<System.DateTime> FechaAntiguedad { get; set; }
        public Nullable<int> ContratoID { get; set; }
        public Nullable<int> TipoRegimenID { get; set; }
        public Nullable<int> SindicatoID { get; set; }
        public string Nacionalidad { get; set; }
        public string VDespensa { get; set; }
        public string Tsangre { get; set; }
        public string Familiaridad { get; set; }
        public string UltPlazaAsig { get; set; }
        public string Titulo { get; set; }
        public string RegistroPatronal { get; set; }
        public Nullable<int> Vacaciones { get; set; }
        public Nullable<int> ZonaHorariaID { get; set; }
        public string ClaveEntFed { get; set; }
        public Nullable<bool> Emailauto { get; set; }
        public Nullable<int> CteID { get; set; }
        public Nullable<double> SBC { get; set; }
        public Nullable<bool> EstaPresente { get; set; }
    }
}
