//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestos
    {
        public int IDpuestos { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IDdepartamento { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> RiesgopuestoID { get; set; }
        public Nullable<int> EmpresaID { get; set; }
    }
}
