//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int ID { get; set; }
        public int EmpresaID { get; set; }
        public string Mov { get; set; }
        public string MovID { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> UltimoCambio { get; set; }
        public string Observaciones { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> EstatusID { get; set; }
        public Nullable<int> Ejercicio { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Personal { get; set; }
        public string HoraRegistro { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> AsisteID { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<bool> RegistroEnTiempo { get; set; }
    }
}
