//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int ID { get; set; }
        public string MovID { get; set; }
        public string Mov { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<int> Ejercicio { get; set; }
        public Nullable<int> Periodo { get; set; }
        public string Observaciones { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<int> EstatusID { get; set; }
        public Nullable<int> SucursalID { get; set; }
        public int EmpresaID { get; set; }
        public Nullable<int> UenID { get; set; }
        public string DepartamentoID { get; set; }
        public Nullable<int> ConceptoID { get; set; }
        public string Modulo { get; set; }
        public Nullable<int> AutorizaID { get; set; }
    }
}
