//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudD
    {
        public int ID { get; set; }
        public string PersonalID { get; set; }
        public Nullable<int> RenglonID { get; set; }
        public Nullable<int> ConceptoID { get; set; }
        public Nullable<System.DateTime> FechaD { get; set; }
        public Nullable<System.DateTime> FechaA { get; set; }
        public string Referencia { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> CantidadPendiente { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<double> Saldo { get; set; }
    }
}
