//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudLog
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Consecutivo { get; set; }
        public string Personal { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string HoraRegistro { get; set; }
    }
}
