//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        public int ID { get; set; }
        public string Sucursal { get; set; }
        public string Nombre { get; set; }
        public string Representante { get; set; }
        public Nullable<int> IDempresa { get; set; }
        public string Clave { get; set; }
        public string Rpatronal { get; set; }
        public string Rfc { get; set; }
        public string Domicilio { get; set; }
        public string Cp { get; set; }
        public Nullable<int> Colonia { get; set; }
        public string Localidad { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Prefijo { get; set; }
        public string Extension { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> ZonaHorariaID { get; set; }
        public string SincroID { get; set; }
    }
}
