//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivesCheckerMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiempo
    {
        public System.DateTime Fecha { get; set; }
        public Nullable<short> NoDia { get; set; }
        public Nullable<byte> Dia { get; set; }
        public Nullable<byte> Mes { get; set; }
        public Nullable<short> Anio { get; set; }
        public string DiaNombre { get; set; }
        public string MesNombre { get; set; }
        public Nullable<byte> NoSemana { get; set; }
        public string Semana { get; set; }
        public string Trimestre { get; set; }
        public string CuaTrimestre { get; set; }
        public string Quincena { get; set; }
        public string Bimestre { get; set; }
        public string Semestre { get; set; }
    }
}
